name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1.2.4
        with:
          version: master
      - run: |
          zig build && zig-cache/bin/endron test.edr
          zig test src/tokenizer.zig
